/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkg8puzzle;

import javax.swing.JButton;

/**
 *
 * @author freak
 */
public class panelPuzzle extends javax.swing.JPanel {

    /**
     * Creates new form panelPuzzle
     */
    public panelPuzzle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        pieza1 = new javax.swing.JButton();
        pieza4 = new javax.swing.JButton();
        pieza7 = new javax.swing.JButton();
        pieza2 = new javax.swing.JButton();
        pieza8 = new javax.swing.JButton();
        pieza5 = new javax.swing.JButton();
        pieza3 = new javax.swing.JButton();
        pieza6 = new javax.swing.JButton();
        pieza9 = new javax.swing.JButton();

        jButton8.setText("<html><h2>1</h2></html>");
        jButton8.setActionCommand("pos00");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        pieza1.setText("<html><h2>1</h2></html>");
        pieza1.setActionCommand("pos00");
        pieza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza1ActionPerformed(evt);
            }
        });

        pieza4.setText("<html><h2>4</h2></html>");
        pieza4.setActionCommand("pos00");
        pieza4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza4ActionPerformed(evt);
            }
        });

        pieza7.setText("<html><h2>7</h2></html>");
        pieza7.setActionCommand("pos00");
        pieza7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza7ActionPerformed(evt);
            }
        });

        pieza2.setText("<html><h2>2</h2></html>");
        pieza2.setActionCommand("pos00");
        pieza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza2ActionPerformed(evt);
            }
        });

        pieza8.setText("<html><h2>8</h2></html>");
        pieza8.setActionCommand("pos00");
        pieza8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza8ActionPerformed(evt);
            }
        });

        pieza5.setText("<html><h2>5</h2></html>");
        pieza5.setActionCommand("pos00");
        pieza5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza5ActionPerformed(evt);
            }
        });

        pieza3.setText("<html><h2>3</h2></html>");
        pieza3.setActionCommand("pos00");
        pieza3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza3ActionPerformed(evt);
            }
        });

        pieza6.setText("<html><h2>6</h2></html>");
        pieza6.setActionCommand("pos00");
        pieza6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza6ActionPerformed(evt);
            }
        });

        pieza9.setActionCommand("pos00");
        pieza9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieza9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieza1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieza4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieza7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieza2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieza5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieza8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieza3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieza6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieza9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pieza3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pieza6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pieza2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pieza5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pieza8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pieza9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pieza1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pieza4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pieza7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pieza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza1ActionPerformed
        //System.out.println(pieza1.getX() + " , " + pieza1.getY());
        
        changePos(pieza1);
    }//GEN-LAST:event_pieza1ActionPerformed

    private void pieza4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza4ActionPerformed
        //System.out.println(pieza4.getX() + " , " + pieza4.getY());
        
        changePos(pieza4);
    }//GEN-LAST:event_pieza4ActionPerformed

    private void pieza7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza7ActionPerformed
        //System.out.println(pieza7.getX() + " , " + pieza7.getY());
        
        changePos(pieza7);
    }//GEN-LAST:event_pieza7ActionPerformed

    private void pieza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza2ActionPerformed
        //System.out.println(pieza2.getX() + " , " + pieza2.getY());
        
        changePos(pieza2);
    }//GEN-LAST:event_pieza2ActionPerformed

    private void pieza8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza8ActionPerformed
        //System.out.println(pieza8.getX() + " , " + pieza8.getY());
        
        changePos(pieza8);
    }//GEN-LAST:event_pieza8ActionPerformed

    private void pieza5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza5ActionPerformed
        //System.out.println(pieza5.getX() + " , " + pieza5.getY());
        
        changePos(pieza5);
    }//GEN-LAST:event_pieza5ActionPerformed

    private void pieza3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza3ActionPerformed
        //System.out.println(pieza3.getX() + " , " + pieza3.getY());
        
        changePos(pieza3);
    }//GEN-LAST:event_pieza3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //System.out.println(pieza7.getX() + " , " + pieza7.getY());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void pieza6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza6ActionPerformed
        //System.out.println(pieza6.getX() + " , " + pieza6.getY());
        
        changePos(pieza6);
    }//GEN-LAST:event_pieza6ActionPerformed

    private void pieza9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieza9ActionPerformed
        //System.out.println(pieza9.getX() + " , " + pieza9.getY());
    }//GEN-LAST:event_pieza9ActionPerformed

    private boolean vecinoVacio (JButton pieza) {
        if((pieza.getX() +66) == pieza9.getX() && pieza.getY() == pieza9.getY()){
            return true;
        }
        if((pieza.getX() -66) == pieza9.getX() && pieza.getY() == pieza9.getY()){
            return true;
        }
        if((pieza.getY() +66) == pieza9.getY() && pieza.getX() == pieza9.getX()){
            return true;
        }
        if((pieza.getY() -66) == pieza9.getY() && pieza.getX() == pieza9.getX()){
            return true;
        }
        return false;
    }
    
    void changePos (JButton cambio) {
        if(!vecinoVacio(cambio)) return;
        
        int x, y;
        x = pieza9.getX();
        y = pieza9.getY();
        
        pieza9.setLocation(cambio.getX(), cambio.getY());
        cambio.setLocation(x, y);
    }

    public void setInicial(String lol){
        int x = 6;
        int y = 6;
        
        pieza1.setLocation(100, 100);
        pieza2.setLocation(166, 100);
        pieza3.setLocation(232, 100);
        pieza4.setLocation(100, 166);
        pieza5.setLocation(166, 166);
        pieza6.setLocation(232, 166);
        pieza7.setLocation(100, 232);
        pieza8.setLocation(166, 232);
        pieza9.setLocation(232, 232);
        
        System.out.println(pieza1.getLocation() + " -- " + pieza9.getLocation());
        
        for (char l : lol.toCharArray()) {
            System.out.println(x + " , " + y + " - " + l);
            switch(l){
                case '1':
                    pieza1.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '2':
                    pieza2.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '3':
                    pieza3.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '4':
                    pieza4.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '5':
                    pieza5.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '6':
                    pieza6.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '7':
                    pieza7.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '8':
                    pieza8.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                case '9':
                    pieza9.setLocation(x, y);
                    System.out.println("Pieza " + l + " puesta");
                    break;
                default:
                    break;
            }
            System.out.println(pieza1.getLocation() + " -- " + pieza9.getLocation());
            if(x == 138){
                x = -60;
                y += 66;
            }
            x += 66;
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton pieza1;
    private javax.swing.JButton pieza2;
    private javax.swing.JButton pieza3;
    private javax.swing.JButton pieza4;
    private javax.swing.JButton pieza5;
    private javax.swing.JButton pieza6;
    private javax.swing.JButton pieza7;
    private javax.swing.JButton pieza8;
    private javax.swing.JButton pieza9;
    // End of variables declaration//GEN-END:variables
}
